import Head from "next/head";
import { wrapStyle } from "./style.css";

export default function Home() {
  return (
    <div className={wrapStyle}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      aaa
      
      <span>im span</span>
      <div>im div</div>
    </div>
  );
}
